version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: resumate_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=resumate_db
      - POSTGRES_USER=resumate_user
      - POSTGRES_PASSWORD=resumate_password
    ports:
      - "5402:5432"

  web:
    build: .
    container_name: resumate_web
    command: gunicorn --bind 0.0.0.0:8000 config.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=django-insecure-production-ready-key-change-me
      - DEBUG=False
      - ALLOWED_HOSTS=localhost,127.0.0.1,web
      - DATABASE_URL=postgres://resumate_user:resumate_password@db:5432/resumate_db
    depends_on:
      - db

volumes:
  postgres_data:
