# Generated by Django 5.2.16 on 2026-07-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ats_scan', 'ATS Scan'), ('bullet_improver', 'Bullet Improver'), ('cover_letter', 'Cover Letter'), ('career_coach', 'Career Coach'), ('interview_prep', 'Interview Q Generator'), ('job_matching', 'Skills Gap Analysis')], max_length=50)),
                ('target_name', models.CharField(blank=True, default='', max_length=255)),
                ('tokens_used', models.IntegerField(default=0)),
                ('latency_ms', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('mocked', 'Mocked')], default='success', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
