# Generated by Django 6.0.7 on 2026-07-16 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_aiactionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiactionlog',
            name='action',
            field=models.CharField(choices=[('ats_scan', 'ATS Scan'), ('bullet_improver', 'Bullet Improver'), ('cover_letter', 'Cover Letter'), ('career_coach', 'Career Coach'), ('interview_prep', 'Interview Q Generator'), ('job_matching', 'Skills Gap Analysis'), ('resume_generator', 'Resume Generator')], max_length=50),
        ),
        migrations.CreateModel(
            name='GeneratedResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('target_job_field', models.CharField(choices=[('software_developer', 'Software Developer'), ('data_analyst', 'Data Analyst'), ('ai_ml_engineer', 'AI/ML Engineer'), ('web_developer', 'Web Developer'), ('cyber_security', 'Cyber Security'), ('cloud_engineer', 'Cloud Engineer'), ('devops_engineer', 'DevOps Engineer'), ('ui_ux_designer', 'UI/UX Designer'), ('graphic_designer', 'Graphic Designer'), ('digital_marketing', 'Digital Marketing'), ('hr', 'HR'), ('accountant', 'Accountant'), ('teacher', 'Teacher'), ('civil_engineer', 'Civil Engineer'), ('mechanical_engineer', 'Mechanical Engineer'), ('electrical_engineer', 'Electrical Engineer'), ('mba', 'MBA'), ('sales', 'Sales'), ('customer_support', 'Customer Support'), ('other', 'Other')], max_length=50)),
                ('target_job_role', models.CharField(max_length=255)),
                ('template', models.CharField(choices=[('modern', 'Modern'), ('minimal', 'Minimal'), ('corporate', 'Corporate'), ('executive', 'Executive'), ('creative', 'Creative')], default='modern', max_length=20)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('generated_content', models.JSONField(blank=True, default=dict)),
                ('ats_score', models.IntegerField(default=0)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
