# Generated by Django 5.2.16 on 2026-07-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0003_alter_aiactionlog_action_generatedresume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiactionlog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('no tokens', 'No Tockens')], default='success', max_length=10),
        ),
    ]
